-- ERP系统 v5.0 完整建库脚本
-- 覆盖: 系统表 + 生产/客户供应商/进销存/人力资源/财务管理/会计凭证/报表中心/质量管理/协同办公/设备管理/售后管理/系统维护
SET NAMES utf8mb4; DROP DATABASE IF EXISTS erp_system; CREATE DATABASE erp_system DEFAULT CHARSET utf8mb4; USE erp_system;

-- ===== 系统用户表 =====
CREATE TABLE sys_user (id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, real_name VARCHAR(50), phone VARCHAR(20), email VARCHAR(100), department VARCHAR(50), status VARCHAR(20) DEFAULT 'pending', permissions TEXT, approved_by BIGINT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 生产模块 =====
CREATE TABLE prod_bom_structure (id BIGINT AUTO_INCREMENT PRIMARY KEY, level VARCHAR(10), product_code VARCHAR(50), product_name VARCHAR(100), spec VARCHAR(100), qty DECIMAL(18,4), unit_price DECIMAL(18,4), loss_rate DECIMAL(10,4), current_stock DECIMAL(18,4), remark TEXT, process_count INT, source VARCHAR(50), process_content TEXT, position_no VARCHAR(50), operation VARCHAR(50), replace_material VARCHAR(100), unit_name VARCHAR(20), backflush_warehouse VARCHAR(50), created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_process_mgmt (id BIGINT AUTO_INCREMENT PRIMARY KEY, process_code VARCHAR(50), process_name VARCHAR(100), process_type VARCHAR(30), workshop VARCHAR(50), description TEXT, standard_hours DECIMAL(10,2), prep_hours DECIMAL(10,2), staff_need INT, equip_need VARCHAR(100), process_cost DECIMAL(18,2), pricing_method VARCHAR(30), unit_price DECIMAL(18,4), is_outsource VARCHAR(5), outsource_price DECIMAL(18,4), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_mrp_calc (id BIGINT AUTO_INCREMENT PRIMARY KEY, calc_code VARCHAR(50), calc_date DATE, plan_start_date DATE, plan_end_date DATE, calc_type VARCHAR(30), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), demand_qty DECIMAL(18,4), current_stock DECIMAL(18,4), in_transit_qty DECIMAL(18,4), allocated_qty DECIMAL(18,4), net_demand DECIMAL(18,4), suggest_purchase DECIMAL(18,4), suggest_produce DECIMAL(18,4), planner VARCHAR(50), calc_status VARCHAR(30), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_design_mgmt (id BIGINT AUTO_INCREMENT PRIMARY KEY, design_code VARCHAR(50), design_name VARCHAR(100), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), version VARCHAR(30), designer VARCHAR(50), design_date DATE, reviewer VARCHAR(50), review_date DATE, approver VARCHAR(50), approve_date DATE, design_status VARCHAR(30), file_path VARCHAR(500), change_record TEXT, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_cost_item (id BIGINT AUTO_INCREMENT PRIMARY KEY, cost_code VARCHAR(50), cost_name VARCHAR(100), cost_type VARCHAR(30), calc_method VARCHAR(50), department VARCHAR(50), allocation_method VARCHAR(50), allocation_rate DECIMAL(10,4), standard_cost DECIMAL(18,4), actual_cost DECIMAL(18,4), diff_amount DECIMAL(18,2), diff_rate DECIMAL(10,4), is_enabled VARCHAR(5), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_quotation (id BIGINT AUTO_INCREMENT PRIMARY KEY, quote_no VARCHAR(50), quote_date DATE, customer_code VARCHAR(50), customer_name VARCHAR(100), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), qty DECIMAL(18,4), unit VARCHAR(20), material_cost DECIMAL(18,2), labor_cost DECIMAL(18,2), manufacture_cost DECIMAL(18,2), manage_cost DECIMAL(18,2), profit_rate DECIMAL(10,4), quote_price DECIMAL(18,4), quote_amount DECIMAL(18,2), validity VARCHAR(30), quote_person VARCHAR(50), audit_status VARCHAR(30), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_bom_list (id BIGINT AUTO_INCREMENT PRIMARY KEY, bom_code VARCHAR(50), bom_name VARCHAR(100), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), bom_version VARCHAR(30), effective_date DATE, expiry_date DATE, creator VARCHAR(50), create_date DATE, reviewer VARCHAR(50), review_date DATE, bom_status VARCHAR(30), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_plan (id BIGINT AUTO_INCREMENT PRIMARY KEY, level VARCHAR(10), plan_id VARCHAR(50), plan_code VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), detail TEXT, status VARCHAR(30), start_date DATE, plan_end_date DATE, plan_qty DECIMAL(18,4), current_qty DECIMAL(18,4), complete_rate DECIMAL(10,4), remain_qty DECIMAL(18,4), priority VARCHAR(10), plan_type VARCHAR(30), workshop VARCHAR(50), leader VARCHAR(50), reviewer VARCHAR(50), review_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_work_order (id BIGINT AUTO_INCREMENT PRIMARY KEY, work_order_no VARCHAR(50), ref_plan_no VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), plan_qty DECIMAL(18,4), actual_qty DECIMAL(18,4), complete_qty DECIMAL(18,4), scrap_qty DECIMAL(18,4), unit VARCHAR(20), workshop VARCHAR(50), production_line VARCHAR(50), leader VARCHAR(50), start_date DATE, plan_end_date DATE, actual_end_date DATE, total_process INT, current_process VARCHAR(50), order_status VARCHAR(30), priority VARCHAR(10), sales_order_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), reviewer VARCHAR(50), review_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_warehousing (id BIGINT AUTO_INCREMENT PRIMARY KEY, in_no VARCHAR(50), ref_work_order VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), plan_in_qty DECIMAL(18,4), actual_in_qty DECIMAL(18,4), unit VARCHAR(20), warehouse VARCHAR(50), location_no VARCHAR(50), in_date DATE, qc_no VARCHAR(50), qc_result VARCHAR(30), handler VARCHAR(50), reviewer VARCHAR(50), review_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_material_requisition (id BIGINT AUTO_INCREMENT PRIMARY KEY, req_no VARCHAR(50), ref_work_order VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), plan_req_qty DECIMAL(18,4), actual_req_qty DECIMAL(18,4), unit VARCHAR(20), warehouse VARCHAR(50), location_no VARCHAR(50), req_date DATE, req_person VARCHAR(50), reviewer VARCHAR(50), review_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_material_return (id BIGINT AUTO_INCREMENT PRIMARY KEY, return_no VARCHAR(50), ref_work_order VARCHAR(50), ref_req_no VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), return_qty DECIMAL(18,4), unit VARCHAR(20), warehouse VARCHAR(50), location_no VARCHAR(50), reason TEXT, return_date DATE, return_person VARCHAR(50), reviewer VARCHAR(50), review_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_material_shortage (id BIGINT AUTO_INCREMENT PRIMARY KEY, record_no VARCHAR(50), work_order_no VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), material_code VARCHAR(50), material_name VARCHAR(100), material_spec VARCHAR(100), demand_qty DECIMAL(18,4), received_qty DECIMAL(18,4), shortage_qty DECIMAL(18,4), unit VARCHAR(20), current_stock DECIMAL(18,4), expected_arrival DATE, shortage_status VARCHAR(30), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_cost_settle (id BIGINT AUTO_INCREMENT PRIMARY KEY, settle_no VARCHAR(50), work_order_no VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), produce_qty DECIMAL(18,4), material_cost DECIMAL(18,2), labor_cost DECIMAL(18,2), manufacture_cost DECIMAL(18,2), outsource_cost DECIMAL(18,2), other_cost DECIMAL(18,2), total_cost DECIMAL(18,2), unit_cost DECIMAL(18,4), standard_cost DECIMAL(18,4), cost_diff DECIMAL(18,2), settle_date DATE, handler VARCHAR(50), reviewer VARCHAR(50), review_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE prod_alarm (id BIGINT AUTO_INCREMENT PRIMARY KEY, alarm_no VARCHAR(50), alarm_type VARCHAR(30), ref_no VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), alarm_content TEXT, alarm_date DATE, alarm_level VARCHAR(20), handler VARCHAR(50), handle_date DATE, handle_result VARCHAR(200), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 客户供应商 =====
CREATE TABLE cust_customer_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, customer_code VARCHAR(50), customer_name VARCHAR(100), customer_type VARCHAR(30), industry VARCHAR(50), region VARCHAR(50), contact_person VARCHAR(50), contact_phone VARCHAR(20), email VARCHAR(100), address VARCHAR(200), credit_limit DECIMAL(18,2), level VARCHAR(20), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE cust_customer_contact (id BIGINT AUTO_INCREMENT PRIMARY KEY, customer_code VARCHAR(50), customer_name VARCHAR(100), contact_name VARCHAR(50), position VARCHAR(30), phone VARCHAR(20), email VARCHAR(100), is_default VARCHAR(5), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE cust_customer_bank (id BIGINT AUTO_INCREMENT PRIMARY KEY, customer_code VARCHAR(50), customer_name VARCHAR(100), bank_name VARCHAR(100), bank_account VARCHAR(50), account_name VARCHAR(100), is_default VARCHAR(5), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE cust_inquiry_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, inquiry_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), inquiry_date DATE, validity_date DATE, sales_person VARCHAR(50), inquiry_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE cust_quotation_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, quote_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), quote_date DATE, validity_date DATE, total_amount DECIMAL(18,2), sales_person VARCHAR(50), audit_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE cust_contract_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, contract_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), contract_date DATE, contract_amount DECIMAL(18,2), payment_method VARCHAR(50), delivery_method VARCHAR(50), sales_person VARCHAR(50), contract_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE supp_supplier_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, supplier_code VARCHAR(50), supplier_name VARCHAR(100), supplier_type VARCHAR(30), contact_person VARCHAR(50), contact_phone VARCHAR(20), email VARCHAR(100), address VARCHAR(200), level VARCHAR(20), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE supp_evaluation (id BIGINT AUTO_INCREMENT PRIMARY KEY, evaluation_no VARCHAR(50), supplier_code VARCHAR(50), supplier_name VARCHAR(100), evaluation_date DATE, quality_score DECIMAL(5,1), delivery_score DECIMAL(5,1), price_score DECIMAL(5,1), total_score DECIMAL(5,1), evaluator VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 进销存管理 =====
CREATE TABLE trade_goods_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, product_code VARCHAR(50), product_name VARCHAR(100), category VARCHAR(50), spec_model VARCHAR(100), unit VARCHAR(20), brand VARCHAR(50), purchase_price DECIMAL(18,4), sale_price DECIMAL(18,4), unit_cost DECIMAL(18,4), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_goods_category (id BIGINT AUTO_INCREMENT PRIMARY KEY, category_code VARCHAR(50), category_name VARCHAR(100), parent_category VARCHAR(50), product_count INT, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_goods_unit (id BIGINT AUTO_INCREMENT PRIMARY KEY, unit_code VARCHAR(50), unit_name VARCHAR(50), unit_group VARCHAR(50), base_unit VARCHAR(20), conversion_rate DECIMAL(18,4), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_warehouse_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, warehouse_code VARCHAR(50), warehouse_name VARCHAR(100), warehouse_type VARCHAR(30), address VARCHAR(200), manager VARCHAR(50), capacity DECIMAL(18,2), used_capacity DECIMAL(18,2), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_purchase_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, purchase_no VARCHAR(50), supplier_code VARCHAR(50), supplier_name VARCHAR(100), purchase_date DATE, total_amount DECIMAL(18,2), buyer VARCHAR(50), purchase_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_purchase_detail (id BIGINT AUTO_INCREMENT PRIMARY KEY, purchase_no VARCHAR(50), line_no INT, product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), qty DECIMAL(18,4), unit VARCHAR(20), unit_price DECIMAL(18,4), amount DECIMAL(18,2), delivery_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_sales_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, sales_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), sales_date DATE, total_amount DECIMAL(18,2), sales_person VARCHAR(50), sales_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_sales_detail (id BIGINT AUTO_INCREMENT PRIMARY KEY, sales_no VARCHAR(50), line_no INT, product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), qty DECIMAL(18,4), unit VARCHAR(20), unit_price DECIMAL(18,4), amount DECIMAL(18,2), delivery_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_delivery_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, delivery_no VARCHAR(50), ref_sales_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), delivery_date DATE, warehouse VARCHAR(50), logistics VARCHAR(50), tracking_no VARCHAR(50), handler VARCHAR(50), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_stock_in_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, in_no VARCHAR(50), in_type VARCHAR(30), ref_no VARCHAR(50), supplier_code VARCHAR(50), warehouse VARCHAR(50), total_amount DECIMAL(18,2), handler VARCHAR(50), in_date DATE, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_stock_in_detail (id BIGINT AUTO_INCREMENT PRIMARY KEY, in_no VARCHAR(50), line_no INT, product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), qty DECIMAL(18,4), unit VARCHAR(20), unit_cost DECIMAL(18,4), amount DECIMAL(18,2), location VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_stock_out_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, out_no VARCHAR(50), out_type VARCHAR(30), ref_no VARCHAR(50), customer_code VARCHAR(50), warehouse VARCHAR(50), total_amount DECIMAL(18,2), handler VARCHAR(50), out_date DATE, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_stock_out_detail (id BIGINT AUTO_INCREMENT PRIMARY KEY, out_no VARCHAR(50), line_no INT, product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), qty DECIMAL(18,4), unit VARCHAR(20), unit_cost DECIMAL(18,4), amount DECIMAL(18,2), location VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_inventory_balance (id BIGINT AUTO_INCREMENT PRIMARY KEY, product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), warehouse VARCHAR(50), location VARCHAR(50), qty DECIMAL(18,4), unit_cost DECIMAL(18,4), total_value DECIMAL(18,2), min_stock DECIMAL(18,4), max_stock DECIMAL(18,4), stock_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_stock_warning (id BIGINT AUTO_INCREMENT PRIMARY KEY, product_code VARCHAR(50), product_name VARCHAR(100), spec_model VARCHAR(100), warehouse VARCHAR(50), current_stock DECIMAL(18,4), min_stock DECIMAL(18,4), warning_type VARCHAR(30), warning_date DATE, handler VARCHAR(50), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_stock_log (id BIGINT AUTO_INCREMENT PRIMARY KEY, log_no VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), warehouse VARCHAR(50), change_type VARCHAR(30), before_qty DECIMAL(18,4), change_qty DECIMAL(18,4), after_qty DECIMAL(18,4), ref_no VARCHAR(50), operator VARCHAR(50), change_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE trade_warehouse_transfer (id BIGINT AUTO_INCREMENT PRIMARY KEY, transfer_no VARCHAR(50), product_code VARCHAR(50), product_name VARCHAR(100), qty DECIMAL(18,4), from_warehouse VARCHAR(50), to_warehouse VARCHAR(50), transfer_date DATE, handler VARCHAR(50), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 人力资源 =====
CREATE TABLE hr_employee_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, emp_no VARCHAR(20), emp_name VARCHAR(50), gender VARCHAR(5), id_card VARCHAR(30), department VARCHAR(50), position VARCHAR(50), entry_date DATE, phone VARCHAR(20), email VARCHAR(100), address VARCHAR(200), emp_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE hr_department_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, dept_code VARCHAR(50), dept_name VARCHAR(100), parent_dept VARCHAR(50), manager VARCHAR(50), headcount INT, current_count INT, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE hr_attendance_record (id BIGINT AUTO_INCREMENT PRIMARY KEY, emp_no VARCHAR(20), emp_name VARCHAR(50), department VARCHAR(50), attendance_date DATE, clock_in VARCHAR(10), clock_out VARCHAR(10), work_hours DECIMAL(5,1), attendance_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE hr_attendance_leave (id BIGINT AUTO_INCREMENT PRIMARY KEY, leave_no VARCHAR(50), emp_no VARCHAR(20), emp_name VARCHAR(50), leave_type VARCHAR(30), start_date DATE, end_date DATE, leave_days DECIMAL(5,1), reason TEXT, approver VARCHAR(50), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE hr_salary_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, salary_no VARCHAR(50), emp_no VARCHAR(20), emp_name VARCHAR(50), department VARCHAR(50), base_salary DECIMAL(18,2), bonus DECIMAL(18,2), deduction DECIMAL(18,2), insurance DECIMAL(18,2), tax DECIMAL(18,2), net_salary DECIMAL(18,2), salary_month VARCHAR(10), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 财务管理 =====
CREATE TABLE finance_account_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, account_code VARCHAR(50), account_name VARCHAR(100), account_type VARCHAR(30), bank_name VARCHAR(100), bank_account VARCHAR(50), balance DECIMAL(18,2), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_income_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, income_no VARCHAR(50), income_type VARCHAR(30), customer_code VARCHAR(50), customer_name VARCHAR(100), amount DECIMAL(18,2), account VARCHAR(50), income_date DATE, handler VARCHAR(50), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_expense_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, expense_no VARCHAR(50), expense_type VARCHAR(30), supplier_code VARCHAR(50), supplier_name VARCHAR(100), amount DECIMAL(18,2), account VARCHAR(50), expense_date DATE, handler VARCHAR(50), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_receivable_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, receivable_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), total_amount DECIMAL(18,2), received_amount DECIMAL(18,2), remain_amount DECIMAL(18,2), due_date DATE, overdue_days INT, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_payable_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, payable_no VARCHAR(50), supplier_code VARCHAR(50), supplier_name VARCHAR(100), total_amount DECIMAL(18,2), paid_amount DECIMAL(18,2), remain_amount DECIMAL(18,2), due_date DATE, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_invoice_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, invoice_no VARCHAR(50), invoice_type VARCHAR(30), customer_name VARCHAR(100), amount DECIMAL(18,2), tax_amount DECIMAL(18,2), total_amount DECIMAL(18,2), invoice_date DATE, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_external_account (id BIGINT AUTO_INCREMENT PRIMARY KEY, account_no VARCHAR(50), account_type VARCHAR(30), ref_no VARCHAR(50), counterparty VARCHAR(100), amount DECIMAL(18,2), tax_amount DECIMAL(18,2), total_amount DECIMAL(18,2), external_status VARCHAR(20), account_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_bad_debt (id BIGINT AUTO_INCREMENT PRIMARY KEY, bad_debt_no VARCHAR(50), customer_code VARCHAR(50), customer_name VARCHAR(100), receivable_amt DECIMAL(18,2), bad_debt_amt DECIMAL(18,2), bad_debt_reason TEXT, bad_debt_status VARCHAR(20), confirm_date DATE, handler VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE finance_write_off (id BIGINT AUTO_INCREMENT PRIMARY KEY, write_off_no VARCHAR(50), bad_debt_no VARCHAR(50), customer_name VARCHAR(100), write_off_amt DECIMAL(18,2), write_off_method VARCHAR(30), approver VARCHAR(50), approve_date DATE, write_off_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 会计凭证 =====
CREATE TABLE voucher_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, voucher_no VARCHAR(50), voucher_word VARCHAR(10), voucher_date DATE, period VARCHAR(10), debit_total DECIMAL(18,2), credit_total DECIMAL(18,2), prepared_by VARCHAR(50), reviewer VARCHAR(50), voucher_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE voucher_detail (id BIGINT AUTO_INCREMENT PRIMARY KEY, voucher_no VARCHAR(50), line_no INT, subject_code VARCHAR(50), subject_name VARCHAR(100), debit_amount DECIMAL(18,2), credit_amount DECIMAL(18,2), summary VARCHAR(200), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE account_subject (id BIGINT AUTO_INCREMENT PRIMARY KEY, subject_code VARCHAR(50), subject_name VARCHAR(100), subject_type VARCHAR(30), level INT, parent_code VARCHAR(50), balance_direction VARCHAR(10), is_enabled VARCHAR(5), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE account_subject_balance (id BIGINT AUTO_INCREMENT PRIMARY KEY, subject_code VARCHAR(50), subject_name VARCHAR(100), period VARCHAR(10), begin_balance DECIMAL(18,2), debit_amount DECIMAL(18,2), credit_amount DECIMAL(18,2), end_balance DECIMAL(18,2), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE account_general_ledger (id BIGINT AUTO_INCREMENT PRIMARY KEY, subject_code VARCHAR(50), subject_name VARCHAR(100), voucher_no VARCHAR(50), voucher_date DATE, summary VARCHAR(200), debit_amount DECIMAL(18,2), credit_amount DECIMAL(18,2), balance_direction VARCHAR(10), balance DECIMAL(18,2), created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 报表中心(part) =====
CREATE TABLE rpt_sales_daily (id BIGINT AUTO_INCREMENT PRIMARY KEY, report_date DATE, product_code VARCHAR(50), product_name VARCHAR(100), customer_name VARCHAR(100), sales_qty DECIMAL(18,4), sales_amount DECIMAL(18,2), sales_person VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE rpt_purchase_daily (id BIGINT AUTO_INCREMENT PRIMARY KEY, report_date DATE, product_code VARCHAR(50), product_name VARCHAR(100), supplier_name VARCHAR(100), purchase_qty DECIMAL(18,4), purchase_amount DECIMAL(18,2), buyer VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 质量管理 =====
CREATE TABLE quality_inspection_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, inspection_no VARCHAR(50), inspection_type VARCHAR(30), product_code VARCHAR(50), product_name VARCHAR(100), batch_no VARCHAR(50), sample_qty INT, pass_qty INT, fail_qty INT, result VARCHAR(20), inspector VARCHAR(50), inspection_date DATE, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE quality_incoming (id BIGINT AUTO_INCREMENT PRIMARY KEY, inspection_no VARCHAR(50), supplier_name VARCHAR(100), product_code VARCHAR(50), product_name VARCHAR(100), batch_no VARCHAR(50), sample_qty INT, pass_qty INT, result VARCHAR(20), inspector VARCHAR(50), inspection_date DATE, status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 协同办公 =====
CREATE TABLE oa_approval_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, approval_no VARCHAR(50), approval_type VARCHAR(30), applicant VARCHAR(50), department VARCHAR(50), ref_no VARCHAR(50), amount DECIMAL(18,2), submit_date DATE, approver VARCHAR(50), approval_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE oa_purchase_approval (id BIGINT AUTO_INCREMENT PRIMARY KEY, approval_no VARCHAR(50), purchase_no VARCHAR(50), supplier_name VARCHAR(100), total_amount DECIMAL(18,2), applicant VARCHAR(50), approver VARCHAR(50), approval_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE oa_notice_main (id BIGINT AUTO_INCREMENT PRIMARY KEY, notice_no VARCHAR(50), title VARCHAR(200), content TEXT, publisher VARCHAR(50), publish_date DATE, notice_type VARCHAR(30), status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 设备管理 =====
CREATE TABLE equip_device (id BIGINT AUTO_INCREMENT PRIMARY KEY, device_code VARCHAR(50), device_name VARCHAR(100), device_type VARCHAR(30), spec_model VARCHAR(100), brand VARCHAR(50), purchase_date DATE, purchase_price DECIMAL(18,2), department VARCHAR(50), leader VARCHAR(50), device_status VARCHAR(20), location VARCHAR(100), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE equip_iot_device (id BIGINT AUTO_INCREMENT PRIMARY KEY, iot_device_code VARCHAR(50), iot_device_name VARCHAR(100), device_type VARCHAR(30), brand VARCHAR(50), model VARCHAR(50), sn_code VARCHAR(50), install_location VARCHAR(100), customer_name VARCHAR(100), iot_status VARCHAR(20), last_comm_time DATETIME, mqtt_topic VARCHAR(200), protocol VARCHAR(30), firmware_ver VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE equip_mqtt_status (id BIGINT AUTO_INCREMENT PRIMARY KEY, device_code VARCHAR(50), device_name VARCHAR(100), customer_name VARCHAR(100), conn_status VARCHAR(20), broker_addr VARCHAR(100), topic VARCHAR(200), last_heartbeat DATETIME, temperature DECIMAL(10,2), humidity DECIMAL(10,2), voltage DECIMAL(10,2), run_status VARCHAR(30), fault_code VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE equip_maintenance (id BIGINT AUTO_INCREMENT PRIMARY KEY, maintain_no VARCHAR(50), device_code VARCHAR(50), device_name VARCHAR(100), maintain_type VARCHAR(30), plan_date DATE, actual_date DATE, content TEXT, staff VARCHAR(50), result VARCHAR(50), next_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 售后管理 =====
CREATE TABLE aftersale_service_order (id BIGINT AUTO_INCREMENT PRIMARY KEY, service_no VARCHAR(50), customer_name VARCHAR(100), contact_person VARCHAR(50), contact_phone VARCHAR(20), device_name VARCHAR(100), fault_desc TEXT, service_type VARCHAR(30), priority VARCHAR(10), service_staff VARCHAR(50), appointment_date DATE, service_fee DECIMAL(18,2), service_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE aftersale_exception (id BIGINT AUTO_INCREMENT PRIMARY KEY, exception_no VARCHAR(50), ref_no VARCHAR(50), customer_name VARCHAR(100), exception_type VARCHAR(30), exception_desc TEXT, found_date DATE, resp_person VARCHAR(50), solution TEXT, handle_result TEXT, exception_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE aftersale_freight_receipt (id BIGINT AUTO_INCREMENT PRIMARY KEY, freight_no VARCHAR(50), ref_service_no VARCHAR(50), transport_mode VARCHAR(30), sender VARCHAR(50), receiver VARCHAR(50), logistics_co VARCHAR(50), tracking_no VARCHAR(50), freight_fee DECIMAL(18,2), goods_name VARCHAR(100), goods_qty DECIMAL(18,4), receipt_status VARCHAR(20), send_date DATE, remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 系统维护 =====
CREATE TABLE sys_stock_cost_adjust (id BIGINT AUTO_INCREMENT PRIMARY KEY, adjust_no VARCHAR(50), adjust_date DATE, product_code VARCHAR(50), product_name VARCHAR(100), before_amount DECIMAL(18,2), after_amount DECIMAL(18,2), diff_amount DECIMAL(18,2), reason TEXT, handler VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE sys_month_end_op (id BIGINT AUTO_INCREMENT PRIMARY KEY, op_code VARCHAR(50), month_period VARCHAR(20), month_end_date DATE, month_end_status VARCHAR(30), operator VARCHAR(50), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE sys_login_log (id BIGINT AUTO_INCREMENT PRIMARY KEY, record_no VARCHAR(50), user_name VARCHAR(50), login_time DATETIME, login_ip VARCHAR(50), login_status VARCHAR(20), remark TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE sys_log_operation (id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50), module VARCHAR(50), action VARCHAR(20), detail TEXT, ip VARCHAR(50), status VARCHAR(20), created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

-- ===== 默认数据 - admin账户(密码BCrypt加密后: admin123) =====
-- BCrypt hash for "admin123": $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
-- 启动时 AuthController @PostConstruct 会自动创建 BCrypt 加密的用户
